language: objective-c
osx_image: xcode9.1

script:
    - xcodebuild -project LNZTreeViewDemo.xcodeproj -scheme LNZTreeView -destination "OS=11.0,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO test ENABLE_TESTABILITY=YES test | xcpretty;